### ISSUE TITLE
Date Command Issue

### ISSUE THREAD

**Issue by double-fault** [Bone-Project/BoneOS#157]
The date command is having an issue printing the month. I do not know the reason for this. Anyone who knows how to solve this issue can do it, and that will be appreciated.

**Comment by srifqi** [comment]
There is a bug in `printk()` when printing `%s %x`.

For example:
I just add something in `bin/uname/opts/main_uname.c` (d4232bddff899f9298dc9c76803dcf4a839cc863) :
```c
printk ("%s %s %s %x\n", VAR_OSNAME, VAR_RELEASE, VAR_PLATFORM, 1);
```

And it shows:
![printk fails to print correctly](https://cloud.githubusercontent.com/assets/4017302/21979330/09cfd878-dc11-11e6-9556-f0c1402538ba.png)

That bug shows after first call.

**Comment by double-fault** [comment]
@srifqi no, that does not prove anything. The bug which you are experiencing is because you are running it on Virtual Box. Try running it on QEmu on a Linux distribution like Ubuntu.

![selection_142](https://cloud.githubusercontent.com/assets/12422882/21981246/7b127c98-dc0c-11e6-8001-73c1dbb2ed17.png)

**Comment by amanuel2** [comment]
VirtualBox is widely used so we will have to support it. I will look into this bug

**Comment by amanuel2** [comment]
@srifqi seems like it is fixed.. tested on virtualbox,qemu,hardware,etc... and seems to work on two computers

**Comment by double-fault** [comment]
@amanuel2 no, it is not yet fixed. Try to do the "date" command, it does not print the month properly. Also, @srifqi was right, I was wrong. If you do `uname -a` twice, with the change srifqi suggested, it prints wrong even in my system. The screen shot I have provided does it only once.

**Comment by amanuel2** [comment]
Date command causes this.. not the uname -a twice thing..

<img src="http://i.imgur.com/Xv2WatO.png"/>

I will fix this date problem

**Comment by srifqi** [comment]
@amanuel2, you haven't changed the code for ```uname -a``` (just for testing) to be like this: https://github.com/Bone-Project/BoneOS/issues/157#issuecomment-272825874

**Comment by amanuel2** [comment]
Solved : https://github.com/Bone-Project/BoneOS/commit/b8918e439be58289751cff828ffc04fe76791859

**Comment by amanuel2** [comment]
the problem was with using char* .. eventually gets tangled up to same adress and causes multiple distaters.. avoid using char* until memory management and use str_t
